//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ck_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class archive_leads
    {
        public int lead_number { get; set; }
        public string project_name { get; set; }
        public string branch_name { get; set; }
        public string customer_firstname { get; set; }
        public string customer_lastname { get; set; }
        public string customer_email { get; set; }
        public string phone_number { get; set; }
        public string emp_firstname { get; set; }
        public string emp_lastname { get; set; }
        public string project_status { get; set; }
        public string delivery_status { get; set; }
        public string source_name { get; set; }
        public string class_name { get; set; }
        public string project_type { get; set; }
        public string jobsite_address { get; set; }
        public string jobsite_city { get; set; }
        public string jobsite_county { get; set; }
        public string jobsite_state { get; set; }
        public string jobsite_zipcode { get; set; }
        public string lead_email { get; set; }
        public string lead_phone_number { get; set; }
        public string second_lead_phone_number { get; set; }
        public System.DateTime lead_date { get; set; }
        public System.DateTime lead_close_date { get; set; }
        public bool tax_exempt { get; set; }
        public bool in_city { get; set; }
        public Nullable<double> building_permit_cost { get; set; }
        public Nullable<double> installation_cost { get; set; }
        public Nullable<double> product_cost { get; set; }
        public Nullable<double> tax_cost { get; set; }
        public Nullable<double> total_cost { get; set; }
    }
}
