//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ck_project
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class lead_log_file
    {
        public int log_number { get; set; }
        [Display(Name = "Username")]
        public string emp_username { get; set; }
        [Display(Name = "Lead Number")]
        public int lead_number { get; set; }
        [Display(Name = "Section Name")]
        public string table_name { get; set; }
        [Display(Name = "Field Changed")]
        public string column_name { get; set; }
        [Display(Name = "Operation")]
        public string action_name { get; set; }
        [Display(Name = "Operation Date")]
        public System.DateTime update_date { get; set; }
        [Display(Name = "Previous Value")]
        public string prvious_value { get; set; }
        [Display(Name = "New Value")]
        public string new_value { get; set; }

        public virtual lead lead { get; set; }
    }
}
