//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ck_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks_installation
    {
        public int tasks_installation_number { get; set; }
        public int task_number { get; set; }
        public int installation_number { get; set; }
        public double hours { get; set; }
        public double m_cost { get; set; }
        public double labor_cost { get; set; }
        public Nullable<double> material_retail_cost { get; set; }
    
        public virtual installation installation { get; set; }
        public virtual task task { get; set; }
    }
}
