//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ck_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxes_leads
    {
        public int taxes_leads_number { get; set; }
        public int tax_number { get; set; }
        public int lead_number { get; set; }
    
        public virtual lead lead { get; set; }
        public virtual tax tax { get; set; }
    }
}
