//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ck_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class total_cost
    {
        public int cost_number { get; set; }
        public Nullable<double> product_cost { get; set; }
        public Nullable<double> installation_cost { get; set; }
        public Nullable<double> total_cost1 { get; set; }
        public int lead_number { get; set; }
        public Nullable<double> tax_cost { get; set; }
        public Nullable<double> building_permit_cost { get; set; }
    
        public virtual lead lead { get; set; }
    }
}
